server:
  address: 3.39.102.199
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: utf-8
    username: "noreplyidcp03300@gmail.com"
    password: "nqwjgogtugperctw"
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/mysql_ex"
    username: hsw
    password: QWERqwer7*
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true

jwt:
  secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45E6AGFsXgFsRhT4YSdSb
logging:
  level:
    org:
      springframework:
        security: DEBUG
