server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#springdoc:
#  packages-to-scan: com.example.indukclubpromotionserver
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    display-request-duration: true
#    operations-sorter: alpha
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/mysql_ex"
    #    url: "jdbc:mysql://localhost:3306/mysql_ex?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
    username: hsw
    password: hsw
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true

jwt:
  secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45E6AGFsXgFsRhT4YSdSb
logging:
  level:
    org:
      springframework:
        security: DEBUG
